### ISSUE TITLE
Compatibility with Flux 0.14

### ISSUE THREAD

**Issue by DoktorMike** [JuliaTrustworthyAI/LaplaceRedux.jl#59]
Hey really cool work!

Is there a reason why 0.14 is not supported? If what needs to be fixed and maybe we can take a stab at it?

**Comment by pat-alt** [comment]
Hi there, thanks! To be honest, I just haven't had time to work on this project for a while and must have missed the compat helper notification (#57), which I have just merged.

**Comment by pat-alt** [comment]
By the way I think you might be interested in [JointEnergyModels.jl](https://github.com/JuliaTrustworthyAI/JointEnergyModels.jl). I've come across your [EnergyBasedModels.jl](https://github.com/DoktorMike/EnergyBasedModels.jl) that's why I'm mentioning it. [JointEnergyModels.jl](https://github.com/JuliaTrustworthyAI/JointEnergyModels.jl) implements joint energy training for Flux models. It's still pretty bare bones at the moment, but if this is of interest then comments/PRs are very welcome 😄

**Comment by DoktorMike** [comment]
> By the way I think you might be interested in [JointEnergyModels.jl](https://github.com/JuliaTrustworthyAI/JointEnergyModels.jl). I've come across your [EnergyBasedModels.jl](https://github.com/DoktorMike/EnergyBasedModels.jl) that's why I'm mentioning it. [JointEnergyModels.jl](https://github.com/JuliaTrustworthyAI/JointEnergyModels.jl) implements joint energy training for Flux models. It's still pretty bare bones at the moment, but if this is of interest then comments/PRs are very welcome 😄

Very cool. Will have a look!
